sudo: required

services:
    - docker

cache:
    directories:
        - "$HOME/google-cloud-sdk/"

before_install:
    - openssl aes-256-cbc -K $encrypted_dee17404e69f_key -iv $encrypted_dee17404e69f_iv -in k8stest-service-account.json.enc -out k8stest-service-account.json -d
    - gcloud version || true
    - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
    # Add gcloud to $PATH
    - gcloud components update kubectl
    - gcloud version
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project k8stest-276107
    - gcloud config set compute/zone europe-west6-b
    - gcloud container clusters get credentials cluster-1
    - docker run -e CI=true cahitbeyaz/docker-react npm run test
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
    - docker build -t cahitbeyaz/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true cahitbeyaz/react-test npm run test

