sudo: required

services:
    - docker

env:
    global:
    # Do not prompt for user input when using any SDK methods.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 
      
before_install:
    - openssl aes-256-cbc -K $encrypted_dee17404e69f_key -iv $encrypted_dee17404e69f_iv -in k8stest-service-account.json.enc -out k8stest-service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud version
    - gcloud auth activate-service-account --key-file k8stest-service-account.json
    - gcloud config set project k8stest-276107
    - gcloud config set compute/zone europe-west6-b
    - gcloud container clusters get-credentials cluster-1
    - docker run -e CI=true cahitbeyaz/docker-react npm run test
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
    - docker build -t cahitbeyaz/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true cahitbeyaz/react-test npm run test

